AppBundle\Entity\Queue:
    type: entity
    table: queue
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        originalid:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: OriginalId
        framestart:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: FrameStart
        frameend:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: FrameEnd
        chunkcount:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ChunkCount
        sessionkey:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: SessionKey
        instancekey:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: InstanceKey
        sourcenode:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: SourceNode
        startdatetime:
            type: datetime
            nullable: true
            column: StartDateTime
        enddatetime:
            type: datetime
            nullable: true
            column: EndDateTime
        status:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: Status
    oneToMany:
        frames:
             targetEntity: Queueframe
             mappedBy: queueid
             cascade: ["persist","merge","remove"]
             orderBy:
                frameno : "asc"
        chunks:
             targetEntity: Queuechunk
             mappedBy: queueid
             cascade: ["persist","merge","remove"]
             orderBy:
                chunkno : "asc"
    lifecycleCallbacks: {  }
